10	DATA X,Y,Z
20	LET X = 3
30	PRINT "HOLA QUE TAL?"; U REM VAR NO DECLARADA Y ES DE TIPO NUMERICO
40	FOR I = 1 TO Z
	50	TAN(A$)	REM FALLO ENCUENTRA UNA LETRA
70	NEXT I
90	RANDOMIZE	REM FALLO AL NO ENCONTRAR RND
100	RESTORE	FALLO AL NO ENCONTRAR READ
110	END