10	DATA X,Y,Z
20	LET X$ = 3	REM FALLO, DISTINTOS TIPOS
30	PRINT "HOLA QUE TAL?"; U$ 
40	FOR I$ = 1 TO Z	REM FALLO, DISTINTOS TIPOS
	50	TAN(Z)
	60	SQR(0) REM FALLO ENCUENTRA 0
70	NEXT 	REM FALLO NO ENCUENTRA EL TOKEN
110	END