
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 12 00:29:09 CEST 2018
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface AnalizadorSintacticoSym {
  /* terminals */
  public static final int TK_REM = 18;
  public static final int TK_INT_SIM = 37;
  public static final int TK_INT = 29;
  public static final int TK_INT_SUS = 38;
  public static final int TK_TAN = 35;
  public static final int TK_ATN = 26;
  public static final int TK_FOR = 6;
  public static final int TK_IGUAL = 42;
  public static final int TK_FN = 39;
  public static final int TK_RND = 31;
  public static final int TK_ON = 14;
  public static final int TK_DATA = 2;
  public static final int TK_DIV = 53;
  public static final int TK_SGN = 32;
  public static final int TK_IF = 10;
  public static final int TK_ID = 36;
  public static final int TK_EXP = 28;
  public static final int TK_SUMA = 50;
  public static final int TK_DIM = 4;
  public static final int TK_NEXT = 13;
  public static final int TK_MENOR = 43;
  public static final int TK_MUL = 52;
  public static final int TK_DIG = 55;
  public static final int TK_RETURN = 20;
  public static final int TK_COS = 27;
  public static final int TK_COMA = 49;
  public static final int TK_MAYOR = 44;
  public static final int TK_PAR_IZQ = 40;
  public static final int TK_CADENA = 56;
  public static final int TK_EL = 54;
  public static final int TK_RANDOMIZE = 16;
  public static final int EOF = 0;
  public static final int TK_LOG = 30;
  public static final int error = 1;
  public static final int TK_TO = 24;
  public static final int TK_SIN = 33;
  public static final int TK_LET = 12;
  public static final int TK_STOP = 22;
  public static final int TK_READ = 17;
  public static final int TK_GOTO = 9;
  public static final int TK_END = 5;
  public static final int TK_DEF = 3;
  public static final int TK_THEN = 23;
  public static final int TK_GOSUB = 8;
  public static final int TK_PRINT = 15;
  public static final int TK_DISTINTO = 47;
  public static final int TK_MAYOR_IGUAL = 46;
  public static final int TK_RESTORE = 19;
  public static final int TK_GO = 7;
  public static final int TK_PAR_DER = 41;
  public static final int TK_STEP = 21;
  public static final int TK_ABS = 25;
  public static final int TK_SQR = 34;
  public static final int TK_PUNTOCOMA = 48;
  public static final int TK_MENOR_IGUAL = 45;
  public static final int TK_INPUT = 11;
  public static final int TK_RESTA = 51;
}

